(() => {
  'use strict';

  const RELEASE = 'bonsai-stable-v2-20260718';
  const KEY = 'bonsai_live_1';
  const DB_NAME = 'bonsai-memorial-v2';
  const DB_STORE = 'snapshots';
  const root = document.getElementById('root');
  const now = () => Date.now();
  const clamp = (n, a, b) => Math.min(b, Math.max(a, Number.isFinite(Number(n)) ? Number(n) : a));
  const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const uid = prefix => `${prefix}-${now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
  const object = value => value && typeof value === 'object' && !Array.isArray(value) ? value : {};
  const array = value => Array.isArray(value) ? value : [];
  const dayKey = date => `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;
  const hash = text => [...String(text)].reduce((a,c) => ((a * 33) ^ c.charCodeAt(0)) >>> 0, 5381);

  const SPECIES = {
    pine: { name:'黒松', emoji:'🌲', rate:1.7, seasonal:[86,78,82,92], description:'力強い幹、荒皮、針葉の葉棚をつくる王道の松柏盆栽。' },
    maple: { name:'山もみじ', emoji:'🍁', rate:2.25, seasonal:[98,88,100,82], description:'芽吹き、青葉、紅葉、寒樹。四季そのものを作品にする。' },
    azalea: { name:'皐月', emoji:'🌸', rate:2.0, seasonal:[100,86,76,70], description:'蕾から満開、花後の剪定まで、花姿と枝骨格を両立させる。' }
  };
  const POTS = [
    {id:'starter',name:'素焼き入門鉢',cost:0,grade:72,color:'#956343'},
    {id:'blue',name:'青嵐釉楕円鉢',cost:1800,grade:88,color:'#427a7d'},
    {id:'black',name:'黒土長方鉢',cost:3400,grade:93,color:'#302b28'},
    {id:'moon',name:'月光白釉鉢',cost:7200,grade:96,color:'#b9b4a8'},
    {id:'old',name:'古渡・琥珀鉢',cost:15000,grade:99,color:'#855038'}
  ];
  const PEOPLE = [
    {name:'榊 玄斎',role:'古典盆栽・宗匠',face:'👴',line:'枝を切るな。迷いを切れ。'},
    {name:'水城 志乃',role:'季節盆栽作家',face:'👩',line:'季節の一瞬を、十年残る枝へ変えなさい。'},
    {name:'橘 蓮',role:'現代盆栽アーティスト',face:'🧑',line:'余白は、切った枝の数ではなく意思で生まれる。'},
    {name:'岩城 岳斗',role:'松柏専門・若手筆頭',face:'👨',line:'葉より先に幹を見ろ。作品の嘘は幹に出る。'},
    {name:'三嶋 宗一郎',role:'全国樹藝会 審査長',face:'🧓',line:'十年後にも立つ姿か。それが審査の最後だ。'},
    {name:'牧村 玲二',role:'樹藝評論家',face:'🧔',line:'技術だけでは景色にならない。履歴を見せてほしい。'},
    {name:'東雲 崇',role:'名木コレクター',face:'🤵',line:'値段ではない。手放したくない理由を買う。'}
  ];
  const PARTS = {
    apex:{name:'頂部',x:.52,y:.20,branch:[.50,.57,.52,.20]},
    first_left:{name:'第一枝',x:.28,y:.47,branch:[.50,.60,.28,.47]},
    second_right:{name:'第二枝',x:.72,y:.42,branch:[.51,.55,.72,.42]},
    third_left:{name:'第三枝',x:.36,y:.34,branch:[.50,.48,.36,.34]},
    back_branch:{name:'背枝',x:.61,y:.31,branch:[.50,.45,.61,.31]},
    front_branch:{name:'前枝',x:.53,y:.48,branch:[.50,.57,.53,.48]},
    trunk:{name:'主幹',x:.50,y:.60,branch:[.50,.79,.50,.33]},
    roots:{name:'根張り・根域',x:.50,y:.77,branch:[.39,.78,.61,.78]}
  };
  const TREE_KEYS = ['id','sp','tree','born','water','last','vit','stress','prune','wire','fert','pot','advanced','lastHealthEvent','createdAt'];

  const basePart = () => ({health:100,foliage:82,pruneLevel:0,wire:0,direction:'none',disease:null,pest:null,deadwood:null,scar:0,updatedAt:now()});
  const baseAdvanced = () => ({parts:Object.fromEntries(Object.keys(PARTS).map(id => [id,basePart()])),shari:{level:0,side:'left',createdAt:0}});
  const baseTree = (sp='pine', name='') => ({
    id:uid('tree'),sp:SPECIES[sp]?sp:'pine',tree:name||`${SPECIES[sp]?.name||'黒松'}・若樹`,born:now(),water:82,last:now(),vit:86,stress:2,prune:0,wire:0,fert:0,pot:'starter',advanced:baseAdvanced(),lastHealthEvent:'',createdAt:now()
  });
  const baseState = () => {
    const first=baseTree();
    return {version:2,started:false,name:'あなた',mentor:0,money:5000,rep:0,owned:['starter'],awards:[],log:[],lastWeek:'',stats:{water:0,prune:0,wire:0,shows:0,snapshots:0},garden:[first],activeTreeId:first.id,...first};
  };

  function normalizePart(raw) {
    const p={...basePart(),...object(raw)};
    p.health=clamp(p.health,0,100);p.foliage=clamp(p.foliage,0,100);p.pruneLevel=Math.round(clamp(p.pruneLevel ?? p.prune,0,3));p.wire=Math.round(clamp(p.wire,0,2));
    p.direction=['none','down','up','left','right','front','back'].includes(p.direction)?p.direction:'none';
    p.disease=['needle_blight','sooty_mold','root_rot'].includes(p.disease)?p.disease:null;
    p.pest=['aphid','spider_mite','scale'].includes(p.pest)?p.pest:null;
    p.deadwood=p.deadwood==='jin'?'jin':null;p.scar=clamp(p.scar,0,3);p.updatedAt=clamp(p.updatedAt,0,Number.MAX_SAFE_INTEGER);return p;
  }
  function normalizeAdvanced(raw) {
    const source=object(raw),parts=object(source.parts),result=baseAdvanced();
    Object.keys(PARTS).forEach(id => result.parts[id]=normalizePart(parts[id]));
    const shari=object(source.shari);result.shari={level:Math.round(clamp(shari.level,0,3)),side:shari.side==='right'?'right':'left',createdAt:clamp(shari.createdAt,0,Number.MAX_SAFE_INTEGER)};return result;
  }
  function normalizeTree(raw, fallbackSp='pine') {
    const source=object(raw),aliases={kuromatsu:'pine','黒松':'pine',yamamomiji:'maple','山もみじ':'maple',satsuki:'azalea','皐月':'azalea'},potAlias={pot01:'starter',pot02:'black',pot03:'blue',pot04:'moon',pot05:'old'};
    const sp=aliases[source.sp]||source.sp||fallbackSp,tree=baseTree(SPECIES[sp]?sp:'pine');
    tree.id=String(source.id||tree.id);tree.sp=SPECIES[sp]?sp:'pine';tree.tree=String(source.tree||source.name||`${SPECIES[tree.sp].name}・若樹`).slice(0,80);
    tree.born=clamp(source.born,0,Number.MAX_SAFE_INTEGER)||now();tree.water=clamp(source.water,0,100);tree.last=clamp(source.last,0,Number.MAX_SAFE_INTEGER)||now();tree.vit=clamp(source.vit,0,100);tree.stress=clamp(source.stress,0,1000);
    tree.prune=Math.round(clamp(source.prune,0,10000));tree.wire=Math.round(clamp(source.wire,0,10000));tree.fert=clamp(source.fert,0,100);tree.pot=potAlias[source.pot]||source.pot;if(!POTS.some(p=>p.id===tree.pot))tree.pot='starter';
    tree.advanced=normalizeAdvanced(source.advanced);tree.lastHealthEvent=typeof source.lastHealthEvent==='string'?source.lastHealthEvent:'';tree.createdAt=clamp(source.createdAt,0,Number.MAX_SAFE_INTEGER)||tree.born;return tree;
  }
  function recordFromState(source) { const record={};TREE_KEYS.forEach(k=>record[k]=structuredCloneSafe(source[k]));return normalizeTree(record,source.sp); }
  function structuredCloneSafe(value){try{return structuredClone(value)}catch{return JSON.parse(JSON.stringify(value))}}
  function normalizeState(raw) {
    const source=object(raw),base=baseState(),state={...base,...source};
    state.version=2;state.started=source.started===true;state.name=String(source.name||'あなた').slice(0,40);state.mentor=Math.round(clamp(source.mentor,0,PEOPLE.length-1));state.money=Math.round(clamp(source.money,0,1e9));state.rep=Math.round(clamp(source.rep,0,1e9));
    const potAlias={pot01:'starter',pot02:'black',pot03:'blue',pot04:'moon',pot05:'old'};state.owned=[...new Set(array(source.owned).map(v=>potAlias[v]||v).filter(v=>POTS.some(p=>p.id===v)))];if(!state.owned.includes('starter'))state.owned.unshift('starter');
    state.awards=array(source.awards).filter(v=>v&&typeof v==='object').slice(0,200);state.log=array(source.log).map(v=>typeof v==='string'?{at:now(),text:v}:v).filter(v=>v&&typeof v==='object').slice(0,200);state.lastWeek=typeof source.lastWeek==='string'?source.lastWeek:'';
    const stats=object(source.stats);state.stats={water:Math.round(clamp(stats.water,0,1e6)),prune:Math.round(clamp(stats.prune,0,1e6)),wire:Math.round(clamp(stats.wire,0,1e6)),shows:Math.round(clamp(stats.shows,0,1e6)),snapshots:Math.round(clamp(stats.snapshots,0,1e6))};
    const garden=array(source.garden).map(v=>normalizeTree(v)).slice(0,3);if(!garden.length)garden.push(normalizeTree(source));state.garden=garden;state.activeTreeId=String(source.activeTreeId||garden[0].id);let active=garden.find(t=>t.id===state.activeTreeId)||garden[0];state.activeTreeId=active.id;Object.assign(state,active);
    if(!state.owned.includes(state.pot))state.owned.push(state.pot);return state;
  }

  let state;
  try { state=normalizeState(JSON.parse(localStorage.getItem(KEY)||'null')); }
  catch (error) { try{localStorage.setItem(`${KEY}_corrupt_backup`,localStorage.getItem(KEY)||'')}catch{} state=baseState(); }
  const ui={tab:'home',modal:null,toast:'',wall:false,selectedSpecies:state.sp||'pine',selectedMentor:state.mentor||0,selectedPart:'apex',careMode:'prune',careLevel:1,direction:'down',deadwood:'jin'};

  function syncActive(){const record=recordFromState(state),index=state.garden.findIndex(t=>t.id===state.activeTreeId);if(index>=0)state.garden[index]=record;else{state.garden.unshift(record);state.activeTreeId=record.id}}
  function save(message){syncActive();localStorage.setItem(KEY,JSON.stringify(state));if(message)log(message);}
  function log(text){state.log.unshift({at:now(),text:String(text)});state.log=state.log.slice(0,200);syncActive();localStorage.setItem(KEY,JSON.stringify(state));}
  function toast(text){ui.toast=String(text);render();clearTimeout(toast.timer);toast.timer=setTimeout(()=>{ui.toast='';render()},1900)}
  function activeTree(){return state.garden.find(t=>t.id===state.activeTreeId)||state.garden[0]}
  function switchTree(id){syncActive();const next=state.garden.find(t=>t.id===id);if(!next)return;state.activeTreeId=next.id;Object.assign(state,normalizeTree(next));save();ui.tab='home';render()}
  function capacity(){return state.rep>=300?3:state.rep>=120?2:1}
  function ageDays(){return Math.max(0,(now()-state.born)/86400000*10)}
  function ageYears(){return ageDays()/365}
  function seasonIndex(){return Math.floor((ageDays()%360)/90)}
  function metrics(){const hours=(now()-state.last)/36e5;const water=clamp(state.water-hours*SPECIES[state.sp].rate,0,100);const stress=Math.max(0,state.stress-ageDays()*.018);const partHealth=Object.values(state.advanced.parts).reduce((a,p)=>a+p.health,0)/Object.keys(PARTS).length;const vit=clamp(state.vit-Math.max(0,35-water)*.34-stress*.12+(state.fert||0)*.35+(partHealth-75)*.08,0,100);const maturity=clamp(10+Math.log10(ageDays()+1)*23+state.prune*3.5+state.wire*2.5,0,100);return{water,stress,vit,maturity,partHealth}}
  function title(){return state.rep>=650?'無形樹藝・名人':state.rep>=420?'名匠':state.rep>=260?'盆栽作家':state.rep>=120?'一級盆栽師':state.rep>=60?'若手盆栽師':'若木の友'}
  function currentPot(){return POTS.find(p=>p.id===state.pot)||POTS[0]}
  function potAffinity(){const matrix={pine:{starter:72,blue:74,black:98,moon:77,old:97},maple:{starter:70,blue:95,black:82,moon:96,old:88},azalea:{starter:72,blue:91,black:78,moon:94,old:90}};return matrix[state.sp][state.pot]||75}
  function issueCounts(){let disease=0,pest=0,wire=0;Object.values(state.advanced.parts).forEach(p=>{if(p.disease)disease++;if(p.pest)pest++;if(p.wire)wire++});return{disease,pest,wire}}
  function score(){const m=metrics(),parts=Object.values(state.advanced.parts),health=parts.reduce((a,p)=>a+p.health,0)/parts.length,foliage=parts.filter((p,i)=>i<6).map(p=>p.foliage),balance=100-Math.min(45,Math.max(...foliage)-Math.min(...foliage)),issues=issueCounts(),deadwood=parts.filter(p=>p.deadwood==='jin').length+(state.advanced.shari.level||0);return Math.round(clamp(m.vit*.19+m.maturity*.21+potAffinity()*.20+SPECIES[state.sp].seasonal[seasonIndex()]*.13+health*.13+balance*.09+Math.min(100,deadwood*16)*.05-issues.disease*8-issues.pest*6-issues.wire*1.5,20,99))}
  function weekKey(){const d=new Date(),start=new Date(d.getFullYear(),0,1);return`${d.getFullYear()}-${Math.ceil((((d-start)/86400000)+start.getDay()+1)/7)}`}

  function maybeHealthEvent(){const today=dayKey(new Date());if(state.lastHealthEvent===today||!state.started)return;state.lastHealthEvent=today;const m=metrics(),seed=hash(`${state.id}-${today}`)%1000/1000,chance=.035+(m.water>92?.06:0)+(m.water<25?.07:0)+(m.stress>40?.06:0);if(seed<chance){const branchIds=Object.keys(PARTS).filter(id=>id!=='trunk'&&id!=='roots'),part=state.advanced.parts[branchIds[hash(today+state.id)%branchIds.length]];if((hash(today+'kind')%2)===0)part.disease=['needle_blight','sooty_mold','root_rot'][hash(today+'d')%3];else part.pest=['aphid','spider_mite','scale'][hash(today+'p')%3];part.health=Math.max(20,part.health-8);log(`${PARTS[Object.keys(state.advanced.parts).find(id=>state.advanced.parts[id]===part)]?.name||'枝'}に異変を確認した。`)}else save()}

  function imagePath(){return `./assets/kuromatsu/base/${state.pot}.webp?v=${RELEASE}`}
  function fallbackSvg(sp=state.sp){const maple=sp==='maple',azalea=sp==='azalea',leaf=maple?'#668b4f':azalea?'#54764f':'#264d31',accent=maple?'#a9573d':azalea?'#d38b9e':'#355f3e';return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 720 900"><defs><radialGradient id="g"><stop stop-color="#273c2d"/><stop offset="1" stop-color="#07100a"/></radialGradient><linearGradient id="t" x2="1" y2="1"><stop stop-color="#8b5937"/><stop offset=".55" stop-color="#4d2f22"/><stop offset="1" stop-color="#2b1a14"/></linearGradient></defs><rect width="720" height="900" fill="url(#g)"/><ellipse cx="360" cy="762" rx="178" ry="28" fill="#0a0d0b" opacity=".7"/><path d="M350 710C318 625 360 555 338 470C322 407 351 341 390 265" fill="none" stroke="url(#t)" stroke-width="54" stroke-linecap="round"/><path d="M345 520C270 475 212 422 164 356M355 430C430 395 492 340 548 282M350 610C420 566 487 520 550 458" fill="none" stroke="#513223" stroke-width="22" stroke-linecap="round"/>${[[165,350,115,70],[270,430,125,76],[420,345,135,78],[535,280,105,66],[520,465,120,72],[382,245,115,74]].map(([x,y,rx,ry],i)=>`<ellipse cx="${x}" cy="${y}" rx="${rx}" ry="${ry}" fill="${i%2?accent:leaf}" opacity=".96"/>`).join('')}${azalea?Array.from({length:25},(_,i)=>`<circle cx="${170+(i*67)%390}" cy="${260+(i*43)%230}" r="${8+i%5}" fill="${i%3?'#e7a7b6':'#f3d4dc'}"/>`).join(''):''}<path d="M190 720H530L496 810H224Z" fill="#302a27"/><rect x="180" y="700" width="360" height="42" rx="12" fill="#39312d"/><ellipse cx="360" cy="710" rx="150" ry="24" fill="#3d5a3c"/></svg>`}
  function artMarkup(){if(state.sp==='pine')return `<figure class="photo-bonsai"><img id="bonsai-artwork" src="${imagePath()}" alt="育成状態を反映する黒松盆栽" decoding="async" draggable="false"></figure>`;return `<div class="species-art">${fallbackSvg()}</div>`}

  function drawOverlay(){const canvas=document.getElementById('state-overlay'),stage=document.querySelector('.tree-stage');if(!canvas||!stage)return;const rect=stage.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(rect.width*dpr)),h=Math.max(1,Math.round(rect.height*dpr));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h}const ctx=canvas.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);drawStateEffects(ctx,rect.width,rect.height)}
  function drawStateEffects(ctx,w,h){const m=metrics(),parts=state.advanced.parts;ctx.save();if(m.water<35){ctx.fillStyle=`rgba(136,92,50,${(35-m.water)/150})`;ctx.fillRect(0,0,w,h)}if(m.vit<55){ctx.fillStyle=`rgba(85,78,48,${(55-m.vit)/180})`;ctx.fillRect(0,0,w,h)}ctx.restore();Object.entries(parts).forEach(([id,p])=>{const meta=PARTS[id],x=meta.x*w,y=meta.y*h;if(p.pruneLevel>0&&id!=='trunk'&&id!=='roots'){ctx.save();ctx.filter=`blur(${8+p.pruneLevel*3}px)`;ctx.fillStyle=`rgba(5,13,8,${.12+p.pruneLevel*.11})`;ctx.beginPath();ctx.ellipse(x,y,w*(.075+p.pruneLevel*.014),h*(.048+p.pruneLevel*.009),0,0,Math.PI*2);ctx.fill();ctx.restore()}if(p.wire&&id!=='roots'){const [x1,y1,x2,y2]=meta.branch;ctx.save();ctx.strokeStyle=p.wire===2?'rgba(177,100,48,.92)':'rgba(190,125,72,.82)';ctx.lineWidth=Math.max(1.2,w*.004*p.wire);ctx.setLineDash([3,3]);ctx.beginPath();ctx.moveTo(x1*w,y1*h);ctx.quadraticCurveTo((x1+x2)*.5*w,(y1+y2)*.5*h-8,x2*w,y2*h);ctx.stroke();ctx.restore()}if(p.disease){ctx.save();const color=p.disease==='sooty_mold'?'rgba(30,24,19,.65)':p.disease==='root_rot'?'rgba(103,67,38,.52)':'rgba(154,106,49,.55)';ctx.fillStyle=color;for(let i=0;i<14;i++){const a=(hash(id+i)%628)/100,r=5+(hash(i+id)%18);ctx.beginPath();ctx.arc(x+Math.cos(a)*r*2,y+Math.sin(a)*r,2+(i%4),0,Math.PI*2);ctx.fill()}ctx.restore()}if(p.pest){ctx.save();ctx.fillStyle=p.pest==='scale'?'#d5c5a2':'#34271f';for(let i=0;i<18;i++){const a=i*2.41,r=6+(i%6)*5;ctx.beginPath();ctx.arc(x+Math.cos(a)*r,y+Math.sin(a)*r*.65,1.1+(i%3)*.35,0,Math.PI*2);ctx.fill()}ctx.restore()}if(p.deadwood==='jin'&&id!=='trunk'&&id!=='roots'){const [x1,y1,x2,y2]=meta.branch;ctx.save();ctx.strokeStyle='rgba(224,214,184,.88)';ctx.lineWidth=Math.max(3,w*.009);ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1*w,y1*h);ctx.quadraticCurveTo((x1+x2)*.5*w,(y1+y2)*.5*h,x2*w,y2*h);ctx.stroke();ctx.restore()}});if(state.advanced.shari.level){ctx.save();ctx.strokeStyle='rgba(225,215,187,.78)';ctx.lineWidth=w*(.008+state.advanced.shari.level*.004);ctx.lineCap='round';const side=state.advanced.shari.side==='right'?1:-1;ctx.beginPath();ctx.moveTo(w*(.50+side*.012),h*.74);ctx.bezierCurveTo(w*(.48+side*.025),h*.63,w*(.52+side*.03),h*.51,w*(.50+side*.018),h*.38);ctx.stroke();ctx.restore()}}

  function mentorTip(){const m=metrics(),issues=issueCounts();if(issues.disease||issues.pest)return'評価より先に異変を止めろ。弱った枝は作品にならない。';if(m.water<38)return'表土ではなく鉢底まで見て、水を決めなさい。';if(m.stress>35)return'今は触る時ではない。待つことも手入れだ。';if(state.prune===0)return'最初の一剪は、十年後の正面を決める。';return'完成を急ぐな。今ある余白を、次の季節まで観察しろ。'}
  function gardenMarkup(){return `<div class="garden-strip">${state.garden.map(t=>`<button class="tree-chip ${t.id===state.activeTreeId?'active':''}" data-switch-tree="${escapeHtml(t.id)}"><b>${escapeHtml(t.tree)}</b><small>${SPECIES[t.sp].name}・${(Math.max(0,(now()-t.born)/86400000*10/365)).toFixed(1)}年</small></button>`).join('')}${state.garden.length<capacity()?`<button class="tree-chip" data-add-tree><b>＋ 新しい若木</b><small>育成枠 ${state.garden.length}/${capacity()}</small></button>`:`<div class="tree-chip"><b>育成枠 ${state.garden.length}/${capacity()}</b><small>${capacity()<3?'名声で枠が増えます':'最大枠'}</small></div>`}</div>`}
  function stageMarkup(){const m=metrics();return `<div class="tree-stage">${artMarkup()}<canvas id="state-overlay" class="state-overlay"></canvas><div class="metrics"><div class="metric"><b>${Math.round(m.water)}%</b><span>水分</span></div><div class="metric"><b>${Math.round(m.vit)}%</b><span>樹勢</span></div><div class="metric"><b>${score()}点</b><span>作品評価</span></div></div></div>`}
  function offerMarkup(){if(state.rep<110||score()<73)return'';const amount=Math.round((score()*210+state.rep*35+currentPot().cost*.55)/100)*100,type=(hash(state.id+weekKey())%2)?'高級ホテルの長期貸出':'蒐集家からの購入希望';return `<div class="offer"><h3>${type}</h3><p>現在の作品評価と受賞歴を見た依頼です。提示額 ¥${amount.toLocaleString()}。</p><button class="btn gold" data-accept-offer="${amount}">${type.includes('貸出')?'貸出を受ける':'売却する'}</button></div>`}
  function homePage(){const m=metrics(),issues=issueCounts();return `${gardenMarkup()}<section class="panel hero"><div class="hero-head"><div><span class="eyebrow">${title()}</span><h1>${escapeHtml(state.tree)}</h1><div class="tree-meta">${SPECIES[state.sp].name}・樹齢 ${ageYears().toFixed(1)}年・${currentPot().name}</div></div><div class="muted" style="font-size:9px;text-align:right">相性 ${potAffinity()}<br>履歴 ${state.stats.snapshots}</div></div>${stageMarkup()}<div class="actions"><button class="action-btn" data-care="water"><span>💧</span>水やり</button><button class="action-btn" data-open-care="prune"><span>✂️</span>部位剪定</button><button class="action-btn" data-open-care="wire"><span>🪢</span>部位針金</button><button class="action-btn" data-care="fert"><span>🌿</span>施肥</button></div></section><div class="mentor"><div class="avatar">${PEOPLE[state.mentor].face}</div><div><b>師匠 ${PEOPLE[state.mentor].name}</b><p>「${mentorTip()}」</p></div></div>${issues.disease||issues.pest?`<div class="alert">病気 ${issues.disease}部位・害虫 ${issues.pest}部位を確認。<button class="btn ghost" data-open-care="health">診断と処置</button></div>`:''}<div class="grid2"><div class="card stat-card"><div class="muted">名声</div><div class="value">${state.rep}</div><small class="muted">${title()}</small></div><div class="card stat-card"><div class="muted">大会出展</div><div class="value">${state.stats.shows}</div><small class="muted">受賞 ${state.awards.filter(a=>a.award!=='選外').length}</small></div></div><button class="btn" data-open-care="deadwood">神・舎利／病害虫／詳細手入れ</button><button class="btn" data-save-snapshot>現在の作品画像を銘木録へ保存</button><button class="btn ghost" data-wall>盆栽と鉢だけで鑑賞</button>${offerMarkup()}`}
  function potsPage(){return `<h1 class="page-title">鉢蔵</h1><p class="page-intro">鉢は額縁ではなく作品の一部です。樹種・季節・樹格との相性が審査へ反映されます。</p><div class="pot-grid">${POTS.map(p=>`<article class="card pot-card ${p.id===state.pot?'current':''}"><div class="pot-visual"><div class="pot-shape" style="--pot:${p.color}"></div></div><h3>${p.name}</h3><p>格 ${p.grade}・現在相性 ${({pine:{starter:72,blue:74,black:98,moon:77,old:97},maple:{starter:70,blue:95,black:82,moon:96,old:88},azalea:{starter:72,blue:91,black:78,moon:94,old:90}}[state.sp][p.id])}</p><div class="price">${p.cost?`¥${p.cost.toLocaleString()}`:'無料'}</div><button class="btn ${p.id===state.pot?'ghost':'primary'}" data-pot="${p.id}" ${p.id===state.pot?'disabled':''}>${p.id===state.pot?'使用中':state.owned.includes(p.id)?'この鉢へ替える':'購入して鉢替え'}</button></article>`).join('')}</div>`}
  function rivals(){const names=[['橘 蓮','現代の余白'],['岩城 岳斗','幹を読む者'],['翠川みのり','紅葉を待つ人'],['風間宗樹','松柏の旅人'],['花守あかり','季節の編者'],['結城庵','古鉢蒐集家']];const seed=hash(weekKey());return names.map((n,i)=>({name:n[0],title:n[1],score:61+((seed*(i+5)*17)%31)}))}
  function showField(){return [...rivals(),{name:state.name,title:title(),score:score(),you:true}].sort((a,b)=>b.score-a.score)}
  function showPage(){const field=showField(),myRank=field.findIndex(v=>v.you)+1,already=state.lastWeek===weekKey();return `<h1 class="page-title">週次評論会</h1><p class="page-intro">同時ログインは不要です。今週のプレイヤー作品と審査場で並び、樹形・樹勢・鉢・病害虫・針金跡まで採点されます。</p><section class="panel card"><div class="score-ring" style="--score:${score()}"><b>${score()}</b></div><p style="text-align:center">暫定 ${myRank}位／${field.length}作品</p>${field.map((r,i)=>`<div class="rank-row ${r.you?'you':''}"><div class="rank-num">${i+1}</div><div><b>${escapeHtml(r.name)}</b><div class="muted" style="font-size:8px">${escapeHtml(r.title)}</div></div><div class="rank-score">${r.score}</div></div>`).join('')}<button class="btn gold" data-enter-show ${already?'disabled':''}>${already?'今週は出展済み':'この作品を出展する'}</button></section><div class="card" style="margin-top:9px"><h3>審査長・三嶋 宗一郎</h3><p>「${score()>=88?'完成度が高い。ただし受賞後こそ次の枝を急ぐな。':score()>=75?'見どころが生まれた。鉢と枝先の緊張をもう一段整えたい。':'樹勢と骨格を優先しなさい。点数のための剪定は作品を浅くする。'}」</p></div>${state.awards.slice(0,5).map(a=>`<div class="award-card card" style="margin-top:8px"><b>${escapeHtml(a.award)}・${a.score}点・${a.rank}位</b><p>${new Date(a.at).toLocaleString('ja-JP')}</p></div>`).join('')}`}
  function peoplePage(){return `<h1 class="page-title">人物</h1><p class="page-intro">師匠、ライバル、審査員、評論家、富豪。それぞれの価値観が作品の評価と依頼へ影響します。</p><div class="people-grid">${PEOPLE.map((p,i)=>`<article class="person-card"><div class="avatar">${p.face}</div><div><h3>${p.name}</h3><div class="muted" style="font-size:9px">${p.role}${i===state.mentor?'・あなたの師匠':''}</div><p class="quote">「${p.line}」</p>${i<2&&i!==state.mentor?`<button class="chip" data-mentor="${i}">この人物を師匠にする</button>`:''}</div></article>`).join('')}</div>`}
  function memorialPage(){return `<h1 class="page-title">銘木録</h1><p class="page-intro">初期姿、剪定後、鉢替え、受賞、病害虫からの回復、売却前。作品の一生を画像と物語で残します。</p><button class="btn primary" data-save-snapshot>現在の姿を記録する</button><div id="memorial-list" class="memorial-list" style="margin-top:10px"><div class="empty" style="grid-column:1/-1">作品画像を読み込んでいます…</div></div><div class="card" style="margin-top:10px"><h3>生涯年表</h3>${state.log.slice(0,20).map(item=>`<p><b>${new Date(item.at||now()).toLocaleString('ja-JP')}</b><br>${escapeHtml(item.text||item.x||'')}</p>`).join('')||'<p>これからの手入れが年表になります。</p>'}</div>`}
  function nav(){return `<nav class="nav"><button class="tab ${ui.tab==='home'?'active':''}" data-tab="home"><span>🌿</span>育成</button><button class="tab ${ui.tab==='pots'?'active':''}" data-tab="pots"><span>🏺</span>鉢</button><button class="tab ${ui.tab==='show'?'active':''}" data-tab="show"><span>🏆</span>大会</button><button class="tab ${ui.tab==='people'?'active':''}" data-tab="people"><span>👥</span>人物</button><button class="tab ${ui.tab==='memorial'?'active':''}" data-tab="memorial"><span>📜</span>銘木録</button></nav>`}
  function shell(){const content={home:homePage,pots:potsPage,show:showPage,people:peoplePage,memorial:memorialPage}[ui.tab]();return `<main class="app-shell" data-app-ready="true"><header class="topbar"><div><div class="brand">BONSAI</div><div class="subtitle">育てた時間が、作品になる。</div></div><div><div class="currency">¥${state.money.toLocaleString()}</div><div class="rankline">名声 ${state.rep}・${title()}</div></div></header>${content}${nav()}</main>${ui.modal?modalMarkup():''}${ui.wall?`<div class="wall"><button class="wall-close" data-close-wall>×</button>${stageMarkup()}</div>`:''}${ui.toast?`<div class="toast">${escapeHtml(ui.toast)}</div>`:''}`}
  function onboarding(){return `<main class="onboard" data-app-ready="true"><h1>BONSAI</h1><p class="tagline">一本の木に、あなたの判断を刻む。</p><div class="choice-list">${Object.entries(SPECIES).map(([id,s])=>`<button class="choice ${ui.selectedSpecies===id?'selected':''}" data-species="${id}"><span class="emoji">${s.emoji}</span><span><b>${s.name}</b><small>${s.description}</small></span></button>`).join('')}</div><h2 style="font:20px Georgia,serif;margin:25px 2px 7px">師匠を選ぶ</h2>${PEOPLE.slice(0,2).map((p,i)=>`<button class="choice ${ui.selectedMentor===i?'selected':''}" data-onboard-mentor="${i}"><span class="emoji">${p.face}</span><span><b>${p.name}</b><small>${p.role}。「${p.line}」</small></span></button>`).join('')}<input id="player-name" class="field" maxlength="24" value="${escapeHtml(state.name==='あなた'?'':state.name)}" placeholder="盆栽師としての名前"><input id="tree-name" class="field" maxlength="40" placeholder="最初の木の銘（空欄でも可）"><button class="btn primary" data-start>この木から始める</button><p class="credit">黒松の実写基準画像はアプリ内ライセンス表記に基づき使用・加工しています。</p></main>`}

  function modalMarkup(){const modal=ui.modal;if(modal==='care')return careModal();if(modal==='new-tree')return newTreeModal();return''}
  function careModal(){const mode=ui.careMode,selected=state.advanced.parts[ui.selectedPart],issues=issueCounts();return `<div class="modal-backdrop" data-close-modal><section class="sheet" onclick="event.stopPropagation()"><h2>${mode==='prune'?'部位剪定':mode==='wire'?'部位針金':mode==='health'?'病害虫の診断と処置':'神・舎利の古木技法'}</h2><p class="lead">画像上の部位単位で記録され、剪定・神・舎利は取り消せません。現在選択：${PARTS[ui.selectedPart].name}</p><div class="part-grid">${Object.entries(PARTS).map(([id,p])=>{const x=state.advanced.parts[id];return`<button class="part-btn ${ui.selectedPart===id?'selected':''}" data-part="${id}"><b>${p.name}</b><small>健康 ${Math.round(x.health)}・葉量 ${Math.round(x.foliage)}${x.disease?'・病気':''}${x.pest?'・害虫':''}${x.deadwood?'・神':''}</small></button>`}).join('')}</div>${mode==='prune'?`<div class="chip-row">${[[1,'軽剪定'],[2,'中剪定'],[3,'強剪定']].map(([v,n])=>`<button class="chip ${ui.careLevel===v?'selected':''}" data-level="${v}">${n}</button>`).join('')}</div><div class="alert">剪定後は取り消せません。対象部位の葉量・健康・シルエットが変化します。</div>`:''}${mode==='wire'?`<div class="chip-row">${[[1,'軽針金'],[2,'強針金']].map(([v,n])=>`<button class="chip ${ui.careLevel===v?'selected':''}" data-level="${v}">${n}</button>`).join('')}</div><div class="chip-row">${[['down','下げる'],['up','上げる'],['left','左へ'],['right','右へ'],['front','手前へ'],['back','奥へ']].map(([v,n])=>`<button class="chip ${ui.direction===v?'selected':''}" data-direction="${v}">${n}</button>`).join('')}</div>`:''}${mode==='health'?`<div class="card" style="margin-top:10px"><h3>${PARTS[ui.selectedPart].name}の診断</h3><p>病気：${selected.disease||'なし'}／害虫：${selected.pest||'なし'}／健康 ${Math.round(selected.health)}</p><p>全体では病気 ${issues.disease}部位・害虫 ${issues.pest}部位です。処置費 ¥600。</p></div>`:''}${mode==='deadwood'?`<div class="chip-row"><button class="chip ${ui.deadwood==='jin'?'selected':''}" data-deadwood="jin">神（枝を白骨化）</button><button class="chip ${ui.deadwood==='shari-left'?'selected':''}" data-deadwood="shari-left">舎利・左</button><button class="chip ${ui.deadwood==='shari-right'?'selected':''}" data-deadwood="shari-right">舎利・右</button></div><div class="alert">古木技法は不可逆です。樹勢が不足すると作品評価と健康を大きく損ないます。</div>`:''}<div class="sheet-actions"><button class="btn ghost" data-close-modal>閉じる</button><button class="btn primary" data-apply-care>${mode==='health'?'処置する':'この内容で確定'}</button></div></section></div>`}
  function newTreeModal(){return `<div class="modal-backdrop" data-close-modal><section class="sheet" onclick="event.stopPropagation()"><h2>新しい若木を迎える</h2><p class="lead">名声に応じた育成枠で、複数の木が同時に時間経過します。</p><div class="choice-list">${Object.entries(SPECIES).map(([id,s])=>`<button class="choice ${ui.selectedSpecies===id?'selected':''}" data-species="${id}"><span class="emoji">${s.emoji}</span><span><b>${s.name}</b><small>${s.description}</small></span></button>`).join('')}</div><input id="new-tree-name" class="field" maxlength="40" placeholder="新しい木の銘"><div class="sheet-actions"><button class="btn ghost" data-close-modal>閉じる</button><button class="btn primary" data-confirm-new-tree>迎える（¥1,200）</button></div></section></div>`}

  function render(){try{root.innerHTML=state.started?shell():onboarding();document.documentElement.dataset.bonsaiReady='true';requestAnimationFrame(()=>{drawOverlay();const img=document.getElementById('bonsai-artwork');if(img){img.addEventListener('load',drawOverlay,{once:true});img.addEventListener('error',()=>{img.src=`data:image/svg+xml;charset=utf-8,${encodeURIComponent(fallbackSvg('pine'))}`},{once:true})}if(ui.tab==='memorial')renderMemorial()})}catch(error){fatal(error)}}
  function fatal(error){console.error('[BONSAI fatal]',error);root.innerHTML=`<main class="boot"><div class="boot__inner"><div class="boot__logo">BONSAI</div><div class="card" style="margin-top:28px"><h3>起動を修復できます</h3><p>作品データは残したまま、古いアプリキャッシュだけを更新します。</p><a class="btn primary" href="./repair.html?v=${RELEASE}">起動キャッシュを修復</a><p class="muted">${escapeHtml(error?.message||error)}</p></div></div></main>`}

  function applyCare(){const part=state.advanced.parts[ui.selectedPart],name=PARTS[ui.selectedPart].name;if(ui.careMode==='prune'){if(ui.selectedPart==='trunk'||ui.selectedPart==='roots')return toast('その部位は剪定対象ではありません');if(!confirm(`${name}を剪定します。切った枝葉は戻りません。`))return;part.pruneLevel=Math.max(part.pruneLevel,ui.careLevel);part.foliage=Math.max(5,part.foliage-[0,12,25,42][ui.careLevel]);part.health=Math.max(20,part.health-[0,1,4,9][ui.careLevel]);part.updatedAt=now();state.prune++;state.stats.prune++;state.stress+=5+ui.careLevel*4;log(`${name}を${['','軽く','中程度に','強く'][ui.careLevel]}剪定した。不可逆の形として記録。`)}
    if(ui.careMode==='wire'){if(ui.selectedPart==='roots')return toast('根域には針金をかけられません');part.wire=ui.careLevel;part.direction=ui.direction;part.updatedAt=now();state.wire++;state.stats.wire++;state.stress+=ui.careLevel*4;log(`${name}へ${ui.careLevel===2?'強':'軽'}針金をかけ、${ui.direction}方向へ整姿した。`)}
    if(ui.careMode==='health'){if(!part.disease&&!part.pest)return toast('選択部位に病害虫はありません');if(state.money<600)return toast('処置費が不足しています');state.money-=600;part.disease=null;part.pest=null;part.health=Math.min(100,part.health+12);part.updatedAt=now();log(`${name}の病害虫を処置し、隔離と通風改善を行った。`)}
    if(ui.careMode==='deadwood'){if(metrics().vit<60)return toast('樹勢60以上でなければ実行できません');if(ui.deadwood==='jin'){if(['trunk','roots'].includes(ui.selectedPart))return toast('神は枝部位を選択してください');if(!confirm(`${name}を神にします。この枝は生きた枝には戻りません。`))return;part.deadwood='jin';part.foliage=0;part.health=0;state.stress+=12;log(`${name}を神として白骨化し、古木表現へ組み込んだ。`)}else{if(!confirm(`主幹に舎利を入れます。元には戻りません。`))return;state.advanced.shari.level=Math.min(3,(state.advanced.shari.level||0)+1);state.advanced.shari.side=ui.deadwood.endsWith('right')?'right':'left';state.advanced.shari.createdAt=now();state.stress+=10;log(`主幹${state.advanced.shari.side==='right'?'右':'左'}側へ舎利を入れた。`)}}
    save();ui.modal=null;render();saveSnapshot(`${name}・${ui.careMode}`);toast('作品状態へ反映しました')}

  function enterShow(){if(state.lastWeek===weekKey())return toast('今週は出展済みです');const field=showField(),rank=field.findIndex(v=>v.you)+1,myScore=score(),award=rank===1?'金賞':rank<=3?'優秀賞':myScore>=76?'入選':'選外',money=rank===1?5200:rank<=3?2700:myScore>=76?1000:250,rep=rank===1?48:rank<=3?27:myScore>=76?11:3;state.money+=money;state.rep+=rep;state.stats.shows++;state.lastWeek=weekKey();state.awards.unshift({at:now(),score:myScore,rank,award,field:field.map(v=>({name:v.name,score:v.score}))});log(`${award}。${field.length}作品中${rank}位、${myScore}点。賞金 ¥${money.toLocaleString()}。`);save();render();saveSnapshot(`大会・${award}`);toast(`${award}・${rank}位・${myScore}点`)}
  function acceptOffer(amount){const isLoan=hash(state.id+weekKey())%2===1;if(isLoan){state.money+=Math.round(amount*.35);state.rep+=8;log(`作品を高級施設へ貸し出し、¥${Math.round(amount*.35).toLocaleString()}と名声を得た。`);save();render();return toast('貸出契約が成立しました')}if(!confirm(`${state.tree}を¥${Number(amount).toLocaleString()}で売却します。銘木録には残ります。`))return;saveSnapshot('売却前');syncActive();state.garden=state.garden.filter(t=>t.id!==state.activeTreeId);state.money+=Number(amount);state.rep+=15;if(!state.garden.length){const tree=baseTree(state.sp);state.garden=[tree]}const next=state.garden[0];state.activeTreeId=next.id;Object.assign(state,next);log(`作品を¥${Number(amount).toLocaleString()}で譲渡し、次の若木へ継承した。`);save();render();toast('売却と継承を記録しました')}

  function openDb(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(DB_STORE))db.createObjectStore(DB_STORE,{keyPath:'id'})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
  async function dbPut(value){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).put(value);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
  async function dbList(){const db=await openDb();return new Promise((resolve,reject)=>{const req=db.transaction(DB_STORE).objectStore(DB_STORE).getAll();req.onsuccess=()=>resolve(req.result.sort((a,b)=>b.at-a.at));req.onerror=()=>reject(req.error)})}
  async function dbDelete(id){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(DB_STORE,'readwrite');tx.objectStore(DB_STORE).delete(id);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}
  function loadImage(src){return new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=reject;img.src=src})}
  function cover(ctx,img,w,h){const scale=Math.max(w/img.naturalWidth,h/img.naturalHeight),dw=img.naturalWidth*scale,dh=img.naturalHeight*scale;ctx.drawImage(img,(w-dw)/2,(h-dh)*.48,dw,dh)}
  async function composeSnapshot(){const canvas=document.createElement('canvas');canvas.width=900;canvas.height=1200;const ctx=canvas.getContext('2d');ctx.fillStyle='#07100a';ctx.fillRect(0,0,900,1200);let src=state.sp==='pine'?imagePath():`data:image/svg+xml;charset=utf-8,${encodeURIComponent(fallbackSvg())}`;try{const img=await loadImage(src);cover(ctx,img,900,1200)}catch{const img=await loadImage(`data:image/svg+xml;charset=utf-8,${encodeURIComponent(fallbackSvg())}`);cover(ctx,img,900,1200)}drawStateEffects(ctx,900,1200);const g=ctx.createLinearGradient(0,0,0,1200);g.addColorStop(0,'rgba(0,0,0,.1)');g.addColorStop(.72,'rgba(0,0,0,.12)');g.addColorStop(1,'rgba(0,0,0,.72)');ctx.fillStyle=g;ctx.fillRect(0,0,900,1200);ctx.fillStyle='#efe9da';ctx.font='38px Georgia';ctx.fillText(state.tree,46,1080);ctx.fillStyle='#a7b2aa';ctx.font='20px -apple-system';ctx.fillText(`${SPECIES[state.sp].name}・${currentPot().name}・評価 ${score()}点`,46,1120);return canvas}
  async function saveSnapshot(reason='手動記録'){try{const canvas=await composeSnapshot(),blob=await new Promise((resolve,reject)=>canvas.toBlob(v=>v?resolve(v):reject(new Error('画像生成に失敗')),'image/jpeg',.86)),item={id:uid('snap'),treeId:state.id,tree:state.tree,species:state.sp,pot:state.pot,score:score(),reason,at:now(),blob};await dbPut(item);const all=await dbList();for(const old of all.slice(30))await dbDelete(old.id);state.stats.snapshots++;save();if(ui.tab==='memorial')renderMemorial();toast('銘木録へ作品画像を保存しました')}catch(error){console.warn('[BONSAI snapshot]',error);toast('画像保存に失敗しました')}}
  async function renderMemorial(){const host=document.getElementById('memorial-list');if(!host)return;try{const items=await dbList();if(!items.length){host.innerHTML='<div class="empty" style="grid-column:1/-1">まだ作品画像がありません。剪定、受賞、鉢替えの節目を保存してください。</div>';return}host.innerHTML=items.map(item=>{const url=URL.createObjectURL(item.blob);return `<article class="memorial-card"><img src="${url}" alt="${escapeHtml(item.tree)}の作品記録"><div class="memorial-body"><b>${escapeHtml(item.reason)}・${item.score}点</b><small>${new Date(item.at).toLocaleString('ja-JP')}</small><button class="chip" data-delete-snapshot="${item.id}">削除</button></div></article>`}).join('')}catch(error){host.innerHTML='<div class="empty" style="grid-column:1/-1">銘木録を読み込めませんでした。</div>'}}

  document.addEventListener('click',event=>{const target=event.target.closest('button,a');if(!target)return;
    if(target.dataset.tab){ui.tab=target.dataset.tab;render();return}
    if(target.dataset.species){ui.selectedSpecies=target.dataset.species;render();return}
    if(target.dataset.onboardMentor!==undefined){ui.selectedMentor=Number(target.dataset.onboardMentor);render();return}
    if(target.dataset.start!==undefined){const player=document.getElementById('player-name')?.value.trim(),treeName=document.getElementById('tree-name')?.value.trim(),tree=baseTree(ui.selectedSpecies,treeName||`${SPECIES[ui.selectedSpecies].name}・若樹`);state=baseState();state.started=true;state.name=player||'あなた';state.mentor=ui.selectedMentor;state.garden=[tree];state.activeTreeId=tree.id;Object.assign(state,tree);save('師匠の案内を受け、最初の若木を迎えた。');render();saveSnapshot('初期状態');return}
    if(target.dataset.care==='water'){state.water=100;state.last=now();state.vit=Math.min(100,state.vit+2);state.stats.water++;save('鉢底から流れるまで水を与えた。');render();toast('水やりを記録しました');return}
    if(target.dataset.care==='fert'){state.fert=Math.min(12,state.fert+1);state.stress+=1.5;save('樹勢と季節を見て施肥した。');render();toast('施肥を記録しました');return}
    if(target.dataset.openCare){ui.careMode=target.dataset.openCare;ui.modal='care';ui.selectedPart=ui.careMode==='deadwood'?'first_left':ui.careMode==='health'?Object.keys(state.advanced.parts).find(id=>state.advanced.parts[id].disease||state.advanced.parts[id].pest)||'apex':'apex';render();return}
    if(target.dataset.part){ui.selectedPart=target.dataset.part;render();return}
    if(target.dataset.level){ui.careLevel=Number(target.dataset.level);render();return}
    if(target.dataset.direction){ui.direction=target.dataset.direction;render();return}
    if(target.dataset.deadwood){ui.deadwood=target.dataset.deadwood;render();return}
    if(target.dataset.applyCare!==undefined){applyCare();return}
    if(target.dataset.closeModal!==undefined||target.classList.contains('modal-backdrop')){ui.modal=null;render();return}
    if(target.dataset.pot){const p=POTS.find(v=>v.id===target.dataset.pot);if(!p)return;if(!state.owned.includes(p.id)){if(state.money<p.cost)return toast('資金が不足しています');state.money-=p.cost;state.owned.push(p.id)}state.pot=p.id;save(`${p.name}へ鉢替えした。`);render();saveSnapshot(`鉢替え・${p.name}`);toast('鉢との組み合わせを更新しました');return}
    if(target.dataset.enterShow!==undefined){enterShow();return}
    if(target.dataset.mentor!==undefined){state.mentor=Number(target.dataset.mentor);save(`師匠を${PEOPLE[state.mentor].name}に定めた。`);render();return}
    if(target.dataset.switchTree){switchTree(target.dataset.switchTree);return}
    if(target.dataset.addTree!==undefined){ui.modal='new-tree';ui.selectedSpecies='pine';render();return}
    if(target.dataset.confirmNewTree!==undefined){if(state.garden.length>=capacity())return toast('現在の名声では育成枠が足りません');if(state.money<1200)return toast('若木の購入資金が不足しています');const name=document.getElementById('new-tree-name')?.value.trim(),tree=baseTree(ui.selectedSpecies,name||`${SPECIES[ui.selectedSpecies].name}・新樹`);syncActive();state.money-=1200;state.garden.push(tree);state.activeTreeId=tree.id;Object.assign(state,tree);ui.modal=null;save('新しい若木を迎え、育成枠へ加えた。');render();saveSnapshot('取得時');return}
    if(target.dataset.wall!==undefined){ui.wall=true;render();return}
    if(target.dataset.closeWall!==undefined){ui.wall=false;render();return}
    if(target.dataset.saveSnapshot!==undefined){saveSnapshot('手動記録');return}
    if(target.dataset.deleteSnapshot){if(confirm('この作品画像を銘木録から削除しますか？'))dbDelete(target.dataset.deleteSnapshot).then(renderMemorial);return}
    if(target.dataset.acceptOffer){acceptOffer(Number(target.dataset.acceptOffer));return}
  });

  window.addEventListener('resize',drawOverlay,{passive:true});
  window.addEventListener('error',event=>{if(!document.documentElement.dataset.bonsaiReady)fatal(event.error||new Error(event.message))},true);
  window.addEventListener('unhandledrejection',event=>{if(!document.documentElement.dataset.bonsaiReady)fatal(event.reason||new Error('起動エラー'))});
  window.BonsaiRelease=RELEASE;
  window.BonsaiPhotos={pine:'./assets/kuromatsu/base/black.webp',pineForPot:id=>`./assets/kuromatsu/base/${POTS.some(p=>p.id===id)?id:'black'}.webp`};

  maybeHealthEvent();
  render();
  setTimeout(()=>{if('serviceWorker'in navigator)navigator.serviceWorker.register(`./sw.js?v=${RELEASE}`,{updateViaCache:'none'}).then(r=>r.update()).catch(e=>console.warn('[BONSAI worker]',e))},1200);
})();